name: Release
on:
  push:
    tags: ['*']
env:
  GITHUB_TAG: ${{ github.ref }}
jobs:
  tests:
    name: Test
    uses: inkapplications/.github/.github/workflows/kmp-checks.yml@1.0.1
  publish:
    name: Publish to Maven Central
    needs: tests
    secrets: inherit
    uses: inkapplications/.github/.github/workflows/kmp-maven-publish.yml@1.0.1
    with:
      version: ${{ github.ref_name }}
      publish-android: true
  draft-release:
    name: Draft Github Release
    needs: [publish]
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref_name }}
          draft: true
          prerelease: false
          body: "See CHANGELOG.md for details"
